### ISSUE TITLE
Throwing an error while using redis-stat on windows.

### ISSUE THREAD

**Issue by prajwal78** [junegunn/redis-stat#41]
![redis-stat_error](https://cloud.githubusercontent.com/assets/10049692/10128499/2f0fb9c6-65d1-11e5-8a70-b12d4b5befdc.jpg)

I get the error as shown in the images above while using redis-stat on windows but redis-stat works fine on Linux. I couldn't figure the exact problem with it as I am just a beginner to Redis. If any help would be appreciated.

**Comment by junegunn** [comment]
You can safely ignore the message. It's the command for determining the size of the terminal screen and you're seeing the message since it's not available on Windows. redis-stat will just use the hard-coded width and height values instead.

I could update redis-stat to skip the command on Windows, but I currently don't have a Windows PC to test it on.

**Comment by prajwal78** [comment]
my problem is redis-stat is not doing the job as it is supposed to do. When I try running this command it doesn't work at all whereby throwing this error. Could you please help me out with it?

**Comment by junegunn** [comment]
Hmm, I see, but as I stated above I don't have a Windows PC. redis-stat should work even when the command failed, so something's wrong but I have no clue. Can you try using the JAR file instead? Does it work?

https://github.com/junegunn/redis-stat/releases/

**Comment by prajwal78** [comment]
Again the same error on windows by doing way preferred by you.

**Comment by prajwal78** [comment]
It worked with executable jar and ruby gem is having problem on windows. Thanks mate for the help!!!

**Comment by junegunn** [comment]
Sounds good, I'll try to fix the windows issue when I get a chance.
