### ISSUE TITLE
Not able to install with ruby 1.9.3p484

### ISSUE THREAD

**Issue by AmreeshTyagi** [junegunn/redis-stat#54]
I was trying to install redis-stat, but getting "LoadError". I am new to ruby, so no idea how to resolve this problem. Do I need to install specific version of ruby to install redis-stat?
![redis-stat issue](https://cloud.githubusercontent.com/assets/19740/17916096/bb3ec8fa-69cd-11e6-821d-3801cca4db58.PNG)

**Comment by junegunn** [comment]
How did you install Ruby? On which OS?

**Comment by junegunn** [comment]
If you have trouble installing it with Ruby, consider using the executable JAR instead. You can download one here: https://github.com/junegunn/redis-stat/releases

**Comment by vishalsharma13** [comment]
Facing same issue while installing redis-stat on linux machine. Your support is required to resolve the issue.

Required Details :-

Os :- Linux
RH version :- Red Hat Enterprise Linux Server release 7.2
gem version -- 2.0.3
ruby version -- ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

Error :- 

gem install redis-stat
Building native extensions.  This could take a while...
ERROR:  Error installing redis-stat:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h


Command to install redis-stat :- gem install redis-stat

In alternate solution, is it possible to monitor the redis on web ui by running jar file.

**Comment by junegunn** [comment]
@vishalsharma13 Try installing ruby-devel; i.e. `yum -y install gcc ruby-devel`

**Comment by vishalsharma13** [comment]
@junegunn  
Hi,

Facing same issue 

yum -y install gcc ruby-devel
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
epel/x86_64/metalink                                                                                                                             | 4.4 kB  00:00:00
local                                                                                                                                            | 2.9 kB  00:00:00
Package gcc-4.8.5-4.el7.x86_64 already installed and latest version
No package ruby-devel available.
Nothing to do

gem install redis-stat
Building native extensions.  This could take a while...
ERROR:  Error installing redis-stat:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h


Gem files will remain installed in /usr/local/share/gems/gems/json-1.8.3 for inspection.
Results logged to /usr/local/share/gems/gems/json-1.8.3/ext/json/ext/generator/gem_make.out


Also please elaborate how to show the UI of Redis-stat in browser after running redis-stat jar. Currently i am unable beacause it use TCP protocol instead of HTTP protocol.

Thanks in Advance.

**Comment by junegunn** [comment]
The error message clearly states that the package was not found and not installed. 

Here's a pointer you might want to take a look at:

http://stackoverflow.com/questions/30665912/no-ruby-devel-in-rhel7

If you still can figure out how to solve the problem, just JAR release.
